"""Shared topology-training helpers used by topology-aware stages.

This module is the training-layer facade over legacy topology-finetune helpers.
It gives new training packages a stable import boundary without treating
``src.topology`` as a pipeline-mechanics namespace.
"""

from __future__ import annotations

from src.pipeline.stages.topology_finetune import (
    TOPOLOGY_FINETUNE_CSV_COLUMNS,
    LocalSubgraphTask,
    ValidationEpochResult,
    _build_best_metrics_payload,
    _build_epoch_csv_row,
    _build_internal_validation_node_sets,
    _empty_internal_validation_summary,
    _evaluate_internal_validation_subgraphs,
    _initialize_train_aggregates,
    _local_subgraph_tasks_for_rank,
    _manual_accumulation_context,
    _model_supports_graph_forward,
    _parse_loss_weight_schedule,
    _reduce_train_stats,
    _resolve_bce_negative_ratio,
    _resolve_compute_clustering_mmd,
    _resolve_edge_chunk_size,
    _resolve_embedding_cache_max_bytes,
    _resolve_epoch_seed,
    _resolve_gradient_accumulation_steps,
    _resolve_internal_validation_compute_clustering_mmd,
    _resolve_internal_validation_compute_spectral_stats,
    _resolve_internal_validation_inference_batch_size,
    _resolve_internal_validation_threshold,
    _resolve_monitor_mode,
    _resolve_monitor_value,
    _resolve_sampling_node_sizes,
    _should_run_internal_validation,
    _squeeze_binary_logits,
    _sync_flag,
    _unwrap_model_for_detached_forward,
    _update_train_aggregates,
    _validate_embedding_cache,
    _validation_topology_loss,
    _zero_topology_losses,
)
from src.topology.finetune_data import build_internal_validation_plan

__all__ = [
    "TOPOLOGY_FINETUNE_CSV_COLUMNS",
    "LocalSubgraphTask",
    "ValidationEpochResult",
    "_build_best_metrics_payload",
    "_build_epoch_csv_row",
    "_build_internal_validation_node_sets",
    "_empty_internal_validation_summary",
    "_evaluate_internal_validation_subgraphs",
    "_initialize_train_aggregates",
    "_local_subgraph_tasks_for_rank",
    "_manual_accumulation_context",
    "_model_supports_graph_forward",
    "_parse_loss_weight_schedule",
    "_reduce_train_stats",
    "_resolve_bce_negative_ratio",
    "_resolve_compute_clustering_mmd",
    "_resolve_edge_chunk_size",
    "_resolve_embedding_cache_max_bytes",
    "_resolve_epoch_seed",
    "_resolve_gradient_accumulation_steps",
    "_resolve_internal_validation_compute_clustering_mmd",
    "_resolve_internal_validation_compute_spectral_stats",
    "_resolve_internal_validation_inference_batch_size",
    "_resolve_internal_validation_threshold",
    "_resolve_monitor_mode",
    "_resolve_monitor_value",
    "_resolve_sampling_node_sizes",
    "_should_run_internal_validation",
    "_squeeze_binary_logits",
    "_sync_flag",
    "_unwrap_model_for_detached_forward",
    "_update_train_aggregates",
    "_validate_embedding_cache",
    "_validation_topology_loss",
    "_zero_topology_losses",
    "build_internal_validation_plan",
]
